### ISSUE TITLE
python3-pt-hub-v1 does not install during upgrade

### ISSUE THREAD

**Issue by rricharz** [pi-top/pi-topHUB-v1#2]
If an earlier version of pt-device-manager or pt-hub has been installed, "sudo apt-get upgrade" will not work properly. "pt-device-manager" is held back.

If "sudo apt-get dist-upgrade" is used to correct this, python3-pt-hub-v1 is not installed properly with the error message:

Selecting previously unselected package python3-pt-hub-v1.
Preparing to unpack .../23-python3-pt-hub-v1_1.0.4-1_armhf.deb ...
Unpacking python3-pt-hub-v1 (1.0.4-1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-doMgcT/23-python3-pt-hub-v1_1.0.4-1_armhf.deb (--unpack):
 trying to overwrite '/usr/lib/python3/dist-packages/pthub/pthub_i2c.py', which is also in package python3-pt-hub 1.0.2-1
Preparing to unpack .../24-python3-pt-hub-v2_1.0.3-1_armhf.deb ...
Unpacking python3-pt-hub-v2 (1.0.3-1) over (1.0.2-1) ...

It appears to be a conflict between python3-pt-hub-v1 and python3-pt-hub-v2

I have not yet found a way to resolve this conflict once it has happened and had to start with a new image.

**Comment by m-roberts** [comment]
Uninstall python3-pt-hub, and install python3-pt-hub-v1.
I will add this to the control file, as this seems to have been an oversight on our part.
